@startuml

'left to right direction
top to bottom direction
'skinparam dpi 300
'skinparam ClassFontSize 18
'skinparam linetype polyline
skinparam linetype ortho
skinparam classPadding 10
skinparam nodesep 25
skinparam ranksep 5

legend bottom left
  <b>Legende</b>
  |<#LightGreen>   | bestehende KDS Module   |
  |<#LightCoral>   | Fokus des Modul Kardiologie |
  |<#LightBlue>    | Umsetzungsstufe 1 - Modul Kardiologie |
  |<#Lavender>     | ISiK (gematik)          |
  |<#LightGoldenRodYellow>  | FHIR-Core R4   |
end legend

package "Allgemeine Patientendaten" as Patientendaten {
  package "KDS_Modul_Basis_Person" as Person #LightGreen {
    class "KDS-Person/Patient" as Patient  {
      + Geschlecht
      + Geburtsdatum
    }
    class "KDS_Vitalstatus" as Vitalstatus {
      + Vitalstatus
      + Datum
      + Intrahospitaler Tod über Fallreferenz Entlassgrund
    }
  }
  package "KDS_Modul_Soziodemographische_Daten" as Demographie #LightGreen {
    class KDS_Herkunft {
      + Geburtsland
    }
  }
  class Lebensmittelpunkt {
    + Code: M49
  }
  class Ethnie {
    + Code: SNOMED
  }
}

package Diagnostik {
  package "KDS_Modul_Seltene_Erkrankungen" as SE #LightGreen {
    class "KDS_BMI" as BMI {}
  }
  package "KDS_Modul_Labor" as KDSLabor #LightGreen {
    class "KDS-Laborbefund" as Laborbefund {
      + Code: LOINC
      + Messwert
    }
  }
  package "KDS_Modul_ICU" as ICU #LightGreen {
    class "KDS_Körpergröße" as Koerpergroesse {
      + Code: LOINC | SNOMED
      + Wert: centimeter
      + Datum
    }
    class "KDS_Körpergewicht" as Koerpergewicht {
      + Code: LOINC | SNOMED
      + Wert: kg
      + Datum
    }
  }
  package "KDS_Modul_Seltene_Erkrankungen" as SE #LightGreen {
    class BMI {
      + Code: LOINC
      + Wert: kg/m2
      + Datum
    }
  }
  package "KDS_Modul_Mikrobiologie" as Mibi #LightGreen {
    class "Multiresistente Erreger" as MultiresistenteErreger {
      + MRGN-Klasse
      + MRE-Klasse
      + Datum
    }
  }
  package "EKG_Metadaten" as EKGMetadaten {
    class "EKG_Parameter" as EKGParameter
    class "EKG_Gerät" as EKGGerät {}
    class "EKG_Kanal" as EKGKanal {}
    class "EKG_Messung" as EKGMessung {}
    class "EKG_Result" as EKGResult {}
  }
  class "Echoparameter/LVEF" as Echoparameter {
    + Code: LOINC
    + Zeitpunkt/Periode
    + Wert: LVEF
    + Einheit: %
    + Referenzintervall
  }
}

class Device #LightGoldenRodYellow {
  + Funktionalitäten
  + Einstellungen
  + Hersteller
  + Seriennummer
}

package Anamnese #LightCoral {

  package KardioDevices {
    class "Implantiertes Device" as IDevice #LightBlue {
      + Patient
      + Status
      + Type: Coding (ICD, CRT, VAD)
    }
    class "DeviceImplantation" as Implantation #LightBlue {
      + Code: OPS
      + Datum
    }
  }

  class Allergie {
    + Substanz
  }

  class "Atherosklerotisches Erstereignis" as Erstereignis #LightBlue {
    + Code: Extension
    + Datum
  }

  class "Krankenhausaufenthalte wegen HF im letzten Jahr" as KHAufenth #LightBlue {
    + Code: SNOMED
    + Anzahl: Integer | CodeableConcept
    + Grund: Herzinsuffizienz (SNOMED)
  }

  package "KDS_Modul_Seltene_Erkrankungen" as SE2 #LightGreen {
    class "KDS_Symptom_Condition_SE" as SESymptom #LightGreen {
      + Severity: Schweregrad
      + bodySite: Anatomische Lokalisation
    }
  }

  class Symptom {

  }

  package "KDS_Modul_Diagnose" as Diagnose #LightGreen {
    class "KDS_Diagnose" as KDSDiagnose {
      + Code: ICD | SNOMED
      + Onset[x]: Beginndatum
      + Feststellungsdatumdatum
      + recordedDate: Dokumentationsdatum
      + Stage: Stadium
    }
  }

  class "Kardio-Diagnose" as KardioDiagnose #LightBlue {
    + Severity: Schweregrad
  }

  class "Anamnestisches Nichtvorliegen" as Nichtvorliegen #LightBlue {
    + Code: ICD | SNOMED
    + Effective[x]: Datum
  }

  package "Weitere Risikofaktoren" as Risikofaktoren {
    class Raucherstatus #LightBlue {
      + Code: SNOMED | LOINC
      + Effective[x]: Datum
      + Wert: CodeableConcept (IPS-VS)
      + Rauchbeginn
      + Rauchdauer
      + Zigaretten pro Tag
      + Packungsjahre
    }
    class "Familiäre Disposition" as Disposition {
      + Condition-Code
    }
    class Alkoholkonsum {
      + Code
      + Häufigkeit
      + Menge
    }
  }
  package "KDS_Modul_Prozedur" as KDSProzedur #LightGreen {
    class "KDS_Prozedur" as Prozedur {
      + Code: OPS | SNOMED
      + Perforned[x]: Durchführungsdatum
      + focalDevice: Device
    }
  }
  package "KDS_Modul_Medikation" as Medikation #LightGreen {
    class "KDS_Medikation" as KDSMedikation {
      + Code
      + Dokumentationsdatum
      + Tagesdosis
    }
  }
  package Skalen {
    class "NYHA-Klasse" as NYHAKlasse #LightBlue {}
    class "Fontaine-Stadium" as FontaineStadium {}
    class "CCS-Grad" as CCSGrad {}
    class "Mod. Rankin-Skala" as MRS #LightBlue {}
    class "Kardio-Risikoscore" as KardioScore #LightBlue {
      + Code
      + Dokumentationsdatum
    }
    package "KDS_Modul_PRO" as PRO #LightGreen {
      class KDS_PRO {
        + Dokumentationsdatum
        + Fragen
        + Antworten
        + Score
      }
    }
  }
}

class FamilyMemberHistory #LightGoldenRodYellow {
  + Patient
  + Datum
  + Alter
  + Relationship
  + Condition-Code
}

class ISIKRaucherstatus #Lavender {}

' Verbinder
Raucherstatus -up-|> ISIKRaucherstatus
IDevice --|> Device
EKGGerät --> Device
KardioDiagnose -left-|> Diagnose
Disposition --> FamilyMemberHistory
Symptom -down-|> SESymptom

' Layout --> Chaotische Anordnung: Ohne Hidden-Verbindungen ist es noch schlimmer.
Diagnose -[hidden]left-> Nichtvorliegen
KardioDevices -[hidden]up--> Risikofaktoren
Prozedur -[hidden]up-> Medikation
Symptom -[hidden]up-> Prozedur
Nichtvorliegen -[hidden]up-> KardioDiagnose
Echoparameter -[hidden]right-> Mibi
Echoparameter -[hidden]left-> EKGMetadaten
Skalen -[hidden]up-> KHAufenth
Diagnostik -[hidden]up-> Patientendaten
SE -[hidden]up-> Mibi
ICU -[hidden]up-> Mibi
PRO -[hidden]left-> KardioScore
PRO -[hidden]up-> NYHAKlasse

@enduml