@startuml KDS Kardiologie
'left to right direction
'top to bottom direction
'skinparam dpi 300
'skinparam ClassFontSize 18
'skinparam linetype polyline
skinparam linetype ortho
'skinparam classPadding 10
'skinparam nodesep 25
'skinparam ranksep 5

legend bottom left
  <b>Legende</b>
  |<#LightGreen>           | Bestehende KDS Module                 |
  |<#LightBlue>            | Umsetzungsstufe 1 - Modul Kardiologie |
  |<#Lavender>             | ISiK (gematik)                        |
end legend

class "Kerndatensatz Kardiologie" as KDSKardio{}

class "Allgemeine Patientendaten" as Patientendaten {}

class Anamnese {}

class Diagnostik {}

class ISIKRaucherstatus #Lavender {}

' ==================================
' ==== Algemeine Patientendaten ====
' ==================================
package "KDS Modul\nBasis" as KDSBasis #LightGreen {
  class "Person/Patient" as Patient  {
    + Geschlecht
    + Geburtsdatum
  }
  class Vitalstatus {
    + Code
    + Dokumentationsdatum
    + Intrahospitaler Tod
  }
  class Prozedur {
    + Code
    + Durchführungsdatum
    + Dokumentationsdatum
  }
  class Medikation {
    + Code
    + Dosis
    + Dokumentationsdatum
  }
  class Diagnose {
      + Code
      + Beginndatum
      + Feststellungsdatumdatum
      + Dokumentationsdatum
      + Stadium
      + Schweregrad
    }
}
package "KDS Modul \nSoziodemographische Daten" as KDSSDD #LightGreen {
  class Geburtsland {
    + Code
  }
}
class Lebensmittelpunkt {
  + Code
  + Dokumentationsdatum
}
class Ethnie {
  + Code
}

' ==================
' ==== Anamnese ====
' ==================

class Vorerkrankung #LightBlue {}

class Symptom {
  + Code
  + Schweregrad
  + Dokumentationsdatum
}

class "Anamnestisches Nichtvorliegen\neiner Diagnose oder Prozedur" as Nichtvorliegen #LightBlue {
  + Code
  + Wert
  + Dokumentationsdatum
}

' ================================
' ==== Weitere Risikofaktoren ====
' ================================

class "Weitere Risikofaktoren" as Risikofaktoren {}
class Raucherstatus #LightBlue {
  + Code
  + Dokumentationsdatum
  + Wert
  + Rauchbeginn
  + Rauchdauer
  + Zigaretten pro Tag
  + Packungsjahre
}
class "Familiäre Disposition" as Disposition {
  + Code
  + Wert
}
class Alkoholkonsum {
  + Code
  + Häufigkeit
  + Menge
}

class "Atherosklerotisches Erstereignis" as Erstereignis #LightBlue {
  + Code
  + Art des Ereignisses
  + Datum
}

class "Krankenhausaufenthalte wegen HF im letzten Jahr" as KHAufenth #LightBlue {
  + Code
  + Anzahl
  + Dokumentationsdatum
}

class "Implantiertes Device" as IDevice #LightBlue {
  + Implantationsdatum
}

class Allergie {
  + Substanz
}

' ================
' ==== Skalen ====
' ================

class Skalen {}
class "NYHA-Klasse" as NYHAKlasse #LightBlue {
  + Code
  + Wert
  + Dokumentationsdatum
}
class "Mod. Rankin-Skala" as MRS #LightBlue {
  + Code
  + Wert
  + Dokumentationsdatum
}
class "Kardio-Risikoscore" as KardioScore #LightBlue {
  + Code
  + Wert
  + Dokumentationsdatum
}
class "Fontaine-Stadium" as FontaineStadium {
  + Code
  + Wert
  + Dokumentationsdatum
}
class "CCS-Grad" as CCSGrad {
  + Code
  + Wert
  + Dokumentationsdatum
}
package "KDS Modul\nPRO" as KDSPRO #LightGreen {
  class PRO {
    + Dokumentationsdatum
    + Fragen
    + Antworten
    + Score
  }
}

' ====================
' ==== Diagnostik ====
' ====================

package "KDS Modul\nLabor" as KDSLabor #LightGreen {
  class Laborwert {
    + Code
    + Wert
    + Dokumentationsdatum
  }
}
package "KDS Modul\nICU" as KDSICU #LightGreen {
  class "Körpergröße" as Koerpergroesse {
    + Code
    + Wert
    + Dokumentationsdatum
  }
  class "Körpergewicht" as Koerpergewicht {
    + Code
    + Wert
    + Dokumentationsdatum
  }
}
package "KDS Modul\nSeltene Erkrankungen" as KDSSE #LightGreen {
  class BMI {
    + Code
    + Wert
    + Dokumentationsdatum
  }
}
package "KDS Modul\nMikrobiologie" as KDSMibi #LightGreen {
  class "Multiresistenter Erreger" as MultiresistenteErreger {
    + Code
    + MRGN-Klasse
    + Datum
  }
}
class "EKG-Metadaten" as EKGMetadaten {}
class "EKG-Gerät" as EKGGeraet {}
class "EKG-Annotation" as EKGAnnotation {
  + Code
  + Wert
  + Dokumentationsdatum
}
class "EKG-Rohdatenreferenz" as EKGReferenz {
  + Referenz
  + Format
  + Aufzeichnungsdatum
}

class Echoparameter {
  + Code
  + Wert
  + Dokumentationsdatum
}

class Device {
  + Code
  + Status
  + Funktionalitäten
  + Einstellungen
  + Hersteller
  + Seriennummer
}

' Verbinder
KDSKardio *-- Patientendaten
KDSKardio *-- Diagnostik
KDSKardio *-- Anamnese

Patientendaten *-- Patient
Patientendaten *-- Vitalstatus
Patientendaten *-- Geburtsland
Patientendaten *-- Lebensmittelpunkt
Patientendaten *-- Ethnie

Anamnese *-- Vorerkrankung
Anamnese *-- Symptom
Anamnese *-- Nichtvorliegen
Anamnese *-- Erstereignis
Anamnese *-- Risikofaktoren
Anamnese *-- IDevice
Anamnese *-- Skalen
Anamnese *-- KHAufenth
Anamnese *-- Allergie

Risikofaktoren *-- Raucherstatus
Risikofaktoren *-- Disposition
Risikofaktoren *-- Alkoholkonsum

Skalen *-- NYHAKlasse
Skalen *-- FontaineStadium
Skalen *-- CCSGrad
Skalen *-- MRS
Skalen *-- KardioScore
Skalen *-- PRO

Diagnostik *-- Echoparameter
Diagnostik *-- MultiresistenteErreger
Diagnostik *-- Koerpergroesse
Diagnostik *-- Koerpergewicht
Diagnostik *-- BMI
Diagnostik *-- Laborwert
Diagnostik *-- EKGMetadaten

EKGMetadaten *-- EKGGeraet
EKGMetadaten *-- EKGAnnotation
EKGMetadaten *-- EKGReferenz

Raucherstatus --|> ISIKRaucherstatus
IDevice --|> Device
EKGGeraet --|> Device
Diagnose --|> Vorerkrankung

Patient -[hidden]down-> Prozedur
Vitalstatus -[hidden]down-> Medikation
Prozedur -[hidden]down-> Diagnose

' Layout --> Chaotische Anordnung: Ohne Hidden-Verbindungen ist es noch schlimmer.
'Diagnose -[hidden]left-> Nichtvorliegen
'KardioDevices -[hidden]up--> Risikofaktoren
'Prozedur -[hidden]up-> Medikation
'Symptom -[hidden]up-> Prozedur
'Nichtvorliegen -[hidden]up-> KardioDiagnose
'Echoparameter -[hidden]right-> Mibi
'Echoparameter -[hidden]left-> EKGMetadaten
'Skalen -[hidden]up-> KHAufenth
'Diagnostik -[hidden]up-> Patientendaten
'SE -[hidden]up-> Mibi
'ICU -[hidden]up-> Mibi
'PRO -[hidden]left-> KardioScore
'PRO -[hidden]up-> NYHAKlasse
@enduml