@startuml

class Patient {}

package Anamnese {
  class Diagnose {
    + Beginndatum
    + Feststellungsdatumdatum
    + Dokumentationsdatum
    + Schweregrad
    + Stadium
  }

  class Symptom {
    + Beginndatum
    + Feststellungsdatumdatum
    + Dokumentationsdatum
    + Schweregrad
  }
  class "Weitere Risikofaktoren" as Risikofaktoren {
    + Dokumentationsdatum
    + Raucherstatus
    + Familiäre Prädisposition
  }
  
  class Prozedur {
    + Durchführungsdatum
    + Dokumentationsdatum
    + Device
  }
  class Medikation {
    + Dokumentationsdatum
    + Tagesdosis
  }

  class "Vitalitätsstatus" as Status {
    + Lebendig
    + Dokumentationsdatum
    + Todesdatum
    + Todesursache
  }
}

package "Berechnete Werte" as BerechneteWerte {
  class "Kardiovaskulärer Risikoscore" as KRScore {
    + Dokumentationsdatum
  }
  class PROM{
    + Dokumentationsdatum
    + Fragen
    + Antworten
    + Score
  }
}

package Diagnostik {
  class EKG {
    + Aufzeichnungsdatum
    + Annotation
    + Interpretation
    + Kurvendaten
  }
  class Labor {}
  class Messwert {
    + Messdatum
    + Wert
    + Einheit
    + Referenzintervall
  }
  class Echo {}
}

package Devices {
  class "Elektronisches Devices" as EDevice {
    + Funktionalitäten
    + Einstellungen
  }
  class Herzschrittmacher {}
  class "Implantierter Defibrillator" as ICD {}
  class "Ventrikuläres Unterstützungssystem" as VAD {}
}
' TODO: Devices generischer? Vielleicht kommen später ja noch weitere dazu

Patient <-- Diagnose
Patient <-- Symptom
Patient <-- Prozedur
Patient <-- Medikation
Patient <-- EKG
Patient <-- Labor
Patient <-- Echo
Patient <-- KRScore
Patient <-- Status
Patient <-- PROM
Patient <-- EDevice
EKG *-- Messwert
Labor *-- Messwert
Echo *-- Messwert
EDevice <|-- Herzschrittmacher
EDevice <|-- ICD
EDevice <|-- VAD
Prozedur --> EDevice

@enduml